repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  name: javascript-home-test
  description: null
  topics: squad-platform-team, mission-platform, product-platform, environment-sandbox
